version: "2"

services:
  web:
    container_name: centos6_php7_xdebug
    image: guytenaerefe/centos-php7-xdebug
    build: ./web
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./web/vhost.d/:/etc/httpd/vhost.d/
      - /var/www/git/:/var/www/git/
  db:
    container_name: percona_1
    image: percona:5.6
    volumes:
      - db_symfony:/var/lib/db_symfony
    expose:
      - 3306
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor 
      MYSQL_USER: root
volumes:
  db_symfony : {}
